import requests
# pip install requests


def currency(code):
    rub = requests.get(f"https://cbu.uz/uz/arkhiv-kursov-valyut/json/{code.upper()}/").json()[0]
    a = {
        'code': rub.get('Ccy'),
        'uz': rub.get('CcyNm_UZ'),
        'uzk': rub.get('CcyNm_UZC'),
        'ru': rub.get('CcyNm_RU'),
        'en': rub.get('CcyNm_EN'),
        'rate': rub.get('Rate'),
        'date': rub.get('Date'),
    }
    return a


print(currency("usd"))

currency_code = {
    'BAA': 'AED',
    "Afg'oniston": 'AFN',
    'Armaniston': 'AMD',
    'Argentina': 'ARS',
    'Avstraliya': 'AUD',
    'Ozarbayjon': 'AZN',
    'Bangladesh': 'BDT',
    'Bolgariya': 'BGN',
    'Bahrayn': 'BHD',
    'Bruney': 'BND',
    'Braziliya': 'BRL',
    'Belorus': 'BYN',
    'Shveytsariya': 'CHF',
    'Xitoy': 'CNY',
    'Kuba': 'CUP',
    'Chexiy': 'CZK',
    'Daniya': 'DKK',
    'Jazoir': 'DZD',
    'Misr': 'EGP',
    'EVRO': 'EUR',
    'Angliya': 'GBP',
    'Gruziya': 'GEL',
    'Vengriya': 'HUF',
    'Indoneziya': 'IDR',
    'Isroil': 'ILS',
    'Hindiston': 'INR',
    'Iroq': 'IQD',
    'Eron': 'IRR',
    'Islandiya': 'ISK',
    'Iordaniya': 'JOD',
    'Yaponiya': 'JPY',
    "Qirg‘iz": 'KGS',
    'Kambodja': 'KHR',
    'Koreya': 'KRW',
    'Quvayt': 'KWD',
    "Qozog‘iston": 'KZT',
    'Laos': 'LAK',
    'Livan': 'LBP',
    'Liviya': 'LYD',
    'Marokash': 'MAD',
    'Moldaviya': 'MDL',
    'Myanma': 'MMK',
    'Mongoliya': 'MNT',
    'Meksika': 'MXN',
    'Malayziya': 'MYR',
    'Norvegiya': 'NOK',
    'Zelandiya': 'NZD',
    'Filippin': 'PHP',
    'Pokiston': 'PKR',
    'Polsha': 'PLN',
    'Qatar': 'QAR',
    'Ruminiya': 'RON',
    'Serbiya': 'RSD',
    'Rossiya': 'RUB',
    'Saudiya': 'SAR',
    'Sudan': 'SDG',
    'Shvetsiya': 'SEK',
    'Singapur': 'SGD',
    'Suriya': 'SYP',
    'Tailand': 'THB',
    'Tojikiston': 'TJS',
    'Turkmaniston': 'TMT',
    'Tunis': 'TND',
    'Turkiya': 'TRY',
    'Ukraina': 'UAH',
    'AQSH': 'USD',
    'Urugvay': 'UYU',
    'Venesuela': 'VES',
    'Vetnam': 'VND',
    'SDR': 'SDR',
    'Yaman': 'YER',
    'Janubiy Afrika': 'ZAR',
}
